VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu-14.04"
  config.vm.network "private_network", ip: "192.168.55.44"

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "vagrant" => ["localhost"]
    }
    ansible.playbook = "provision.yml"
  end

  config.vm.provision "file", source: "packer.json", destination: "packer.json"

end
